name: code_quality
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  code_quality:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Run .NET Code Analysis
        uses: dotnet/code-analysis@v1
        id: code-analysis
        with:
          projects: src\*.csproj
          build-breaking: true
          security: 8.0-all
          performance: 8.0-all
          all-categories: 8.0-all
